name: Setup & Run Integration Test Suite

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Setup & Run Integration Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: webfactory/ssh-agent@v0.4.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY_READ }}

      - name: Build
        run: |
          git clone https://github.com/ethereum-optimism/optimism-integration.git \
              $HOME/optimism-integration \
              --recurse-submodules
          cd $HOME/optimism-integration
          BRANCH=${GITHUB_REF##*/}
          ./build.sh -s go-ethereum -b $BRANCH

      - name: Test
        run: |
          cd $HOME/optimism-integration
          BRANCH=${GITHUB_REF##*/}
          GETH_L2_TAG=$BRANCH ./test.sh
